version: "3.7"
services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker_db
    volumes:
      - ./api/db/data:/var/lib/mysql
      - ./api/db/script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  api:
    image: "node:18.18.0-slim"
    working_dir: /home/node/app
    command: "npm start"
    container_name: node-container
    restart: always
    volumes:
      - ./api:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - db
  web:
    image: "php:7.3.33-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
      - api